spring.main.banner-mode=off

server.port=7080

spring.ai.mcp.server.name=test-mcp-servelet
spring.ai.mcp.server.version=0.0.1

spring.ai.mcp.server.protocol=SSE

logging.file.name=./starter-webmvc-server.log
