server.port=7081

spring.ai.mcp.server.name=test-mcp-webflux
spring.ai.mcp.server.version=0.0.1

spring.ai.mcp.server.protocol=STREAMABLE
#spring.ai.mcp.server.protocol=SSE
logging.file.name=./starter-webflux-server.log
